version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "9090:9090"
    volumes:
      - .:/app
      - /:/host
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/vulnerable_db
      - DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - db
    privileged: true
    cap_add:
      - ALL

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=vulnerable_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local
  