version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /tmp/uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/vulnerable_db
      - DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - db
    # No resource limits specified
    # No healthcheck configured
    privileged: true  # Deliberately insecure

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=vulnerable_db
    ports:
      - "5432:5432"  # Exposing database port to host
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # No resource limits
    # World-readable volume permissions

volumes:
  pgdata:
    driver: local  # Using local driver without encryption
