apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  # Security Issue: Sensitive data in ConfigMap instead of Secrets
  DATABASE_URL: "postgresql://admin:admin123@db:5432/vulnerable_db"
  API_KEY: "sk_test_1234567890abcdef"
  ADMIN_PASSWORD: "super_secret_admin_pass"
  # Security Issue: Debug configuration exposed
  DEBUG: "true"
  FLASK_ENV: "development"
  # Security Issue: Internal infrastructure information exposed
  INTERNAL_SERVICES: |
    auth-service: http://auth-service.internal:8080
    payment-service: http://payment-service.internal:8081
    admin-dashboard: http://admin.internal:8082
