apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app-service
  namespace: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  - port: 9090
    targetPort: 9090
    name: debug
  selector:
    app: vulnerable-app
