name: Trivy Code Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read 
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          scanners: 'vuln,secret,config'
          skip-dirs: 'k8s'
          skip-files: 'Dockerfile'
          format: 'json'
          output: 'result.json'

      - name: Add Trivy report as a comment to PR
        uses: domstolene/trivy-pr-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
