name: Trivy Code Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          scanners: 'vuln,secret,config'
          skip-dirs: 'k8s'
          skip-files: 'Dockerfile'
          format: 'json'
          output: 'result.json'

      - name: Generate readable report
        run: |
          trivy --input result.json --format table > trivy-report.txt

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
